### ISSUE TITLE
Change licensing to dual license GPLv3 & PCL

### ISSUE THREAD

**Issue by brusch** [pimcore/quill-bundle#3]
- composer.json
- License.md
- Source file headers 

See also: 
https://github.com/pimcore/pimcore/blob/11.x/LICENSE.md
https://github.com/pimcore/data-hub/blob/1.x/composer.json#L3
https://github.com/pimcore/data-hub/blob/1.x/src/Configuration/Dao.php#L13

**Comment by robertSt7** [comment]
fixed by https://github.com/pimcore/quill-bundle/commit/32e67959ed09290f84c78c67e1f0aa98a85e9446
